export interface Language {
  code: string;
  name: string;
  dictionary: Record<string, string>;
}

// Comprehensive translation dictionaries for demonstration
const englishToSpanish: Record<string, string> = {
  hello: "hola",
  goodbye: "adiós",
  thank: "gracias",
  you: "usted",
  please: "por favor",
  yes: "sí",
  no: "no",
  good: "bueno",
  bad: "malo",
  morning: "mañana",
  night: "noche",
  love: "amor",
  friend: "amigo",
  family: "familia",
  water: "agua",
  food: "comida",
  house: "casa",
  car: "coche",
  book: "libro",
  computer: "computadora",
  work: "trabajo",
  school: "escuela",
  happy: "feliz",
  sad: "triste",
  big: "grande",
  small: "pequeño",
  beautiful: "hermoso",
  welcome: "bienvenido",
  how: "cómo",
  what: "qué",
  where: "dónde",
  when: "cuándo",
  why: "por qué",
  who: "quién",
  the: "el",
  and: "y",
  or: "o",
  is: "es",
  are: "son",
  this: "esto",
  that: "eso",
  my: "mi",
  your: "tu",
  we: "nosotros",
  they: "ellos",
  today: "hoy",
  tomorrow: "mañana",
  yesterday: "ayer",
};

const englishToFrench: Record<string, string> = {
  hello: "bonjour",
  goodbye: "au revoir",
  thank: "merci",
  you: "vous",
  please: "s'il vous plaît",
  yes: "oui",
  no: "non",
  good: "bon",
  bad: "mauvais",
  morning: "matin",
  night: "nuit",
  love: "amour",
  friend: "ami",
  family: "famille",
  water: "eau",
  food: "nourriture",
  house: "maison",
  car: "voiture",
  book: "livre",
  computer: "ordinateur",
  work: "travail",
  school: "école",
  happy: "heureux",
  sad: "triste",
  big: "grand",
  small: "petit",
  beautiful: "beau",
  welcome: "bienvenue",
  how: "comment",
  what: "quoi",
  where: "où",
  when: "quand",
  why: "pourquoi",
  who: "qui",
  the: "le",
  and: "et",
  or: "ou",
  is: "est",
  are: "sont",
  this: "ceci",
  that: "cela",
  my: "mon",
  your: "votre",
  we: "nous",
  they: "ils",
  today: "aujourd'hui",
  tomorrow: "demain",
  yesterday: "hier",
};

const englishToGerman: Record<string, string> = {
  hello: "hallo",
  goodbye: "auf wiedersehen",
  thank: "danke",
  you: "sie",
  please: "bitte",
  yes: "ja",
  no: "nein",
  good: "gut",
  bad: "schlecht",
  morning: "morgen",
  night: "nacht",
  love: "liebe",
  friend: "freund",
  family: "familie",
  water: "wasser",
  food: "essen",
  house: "haus",
  car: "auto",
  book: "buch",
  computer: "computer",
  work: "arbeit",
  school: "schule",
  happy: "glücklich",
  sad: "traurig",
  big: "groß",
  small: "klein",
  beautiful: "schön",
  welcome: "willkommen",
  how: "wie",
  what: "was",
  where: "wo",
  when: "wann",
  why: "warum",
  who: "wer",
  the: "der",
  and: "und",
  or: "oder",
  is: "ist",
  are: "sind",
  this: "dies",
  that: "das",
  my: "mein",
  your: "ihr",
  we: "wir",
  they: "sie",
  today: "heute",
  tomorrow: "morgen",
  yesterday: "gestern",
};

const englishToJapanese: Record<string, string> = {
  hello: "こんにちは",
  goodbye: "さようなら",
  thank: "ありがとう",
  you: "あなた",
  please: "お願いします",
  yes: "はい",
  no: "いいえ",
  good: "良い",
  bad: "悪い",
  morning: "朝",
  night: "夜",
  love: "愛",
  friend: "友達",
  family: "家族",
  water: "水",
  food: "食べ物",
  house: "家",
  car: "車",
  book: "本",
  computer: "コンピュータ",
  work: "仕事",
  school: "学校",
  happy: "幸せ",
  sad: "悲しい",
  big: "大きい",
  small: "小さい",
  beautiful: "美しい",
  welcome: "ようこそ",
  how: "どう",
  what: "何",
  where: "どこ",
  when: "いつ",
  why: "なぜ",
  who: "誰",
  the: "",
  and: "と",
  or: "または",
  is: "です",
  are: "です",
  this: "これ",
  that: "それ",
  my: "私の",
  your: "あなたの",
  we: "私たち",
  they: "彼ら",
  today: "今日",
  tomorrow: "明日",
  yesterday: "昨日",
};

const englishToItalian: Record<string, string> = {
  hello: "ciao",
  goodbye: "arrivederci",
  thank: "grazie",
  you: "lei",
  please: "per favore",
  yes: "sì",
  no: "no",
  good: "buono",
  bad: "cattivo",
  morning: "mattina",
  night: "notte",
  love: "amore",
  friend: "amico",
  family: "famiglia",
  water: "acqua",
  food: "cibo",
  house: "casa",
  car: "auto",
  book: "libro",
  computer: "computer",
  work: "lavoro",
  school: "scuola",
  happy: "felice",
  sad: "triste",
  big: "grande",
  small: "piccolo",
  beautiful: "bello",
  welcome: "benvenuto",
  how: "come",
  what: "cosa",
  where: "dove",
  when: "quando",
  why: "perché",
  who: "chi",
  the: "il",
  and: "e",
  or: "o",
  is: "è",
  are: "sono",
  this: "questo",
  that: "quello",
  my: "mio",
  your: "tuo",
  we: "noi",
  they: "loro",
  today: "oggi",
  tomorrow: "domani",
  yesterday: "ieri",
};

const englishToPortuguese: Record<string, string> = {
  hello: "olá",
  goodbye: "adeus",
  thank: "obrigado",
  you: "você",
  please: "por favor",
  yes: "sim",
  no: "não",
  good: "bom",
  bad: "mau",
  morning: "manhã",
  night: "noite",
  love: "amor",
  friend: "amigo",
  family: "família",
  water: "água",
  food: "comida",
  house: "casa",
  car: "carro",
  book: "livro",
  computer: "computador",
  work: "trabalho",
  school: "escola",
  happy: "feliz",
  sad: "triste",
  big: "grande",
  small: "pequeno",
  beautiful: "bonito",
  welcome: "bem-vindo",
  how: "como",
  what: "o que",
  where: "onde",
  when: "quando",
  why: "por que",
  who: "quem",
  the: "o",
  and: "e",
  or: "ou",
  is: "é",
  are: "são",
  this: "isto",
  that: "isso",
  my: "meu",
  your: "seu",
  we: "nós",
  they: "eles",
  today: "hoje",
  tomorrow: "amanhã",
  yesterday: "ontem",
};

const englishToChinese: Record<string, string> = {
  hello: "你好",
  goodbye: "再见",
  thank: "谢谢",
  you: "你",
  please: "请",
  yes: "是",
  no: "不",
  good: "好",
  bad: "坏",
  morning: "早上",
  night: "晚上",
  love: "爱",
  friend: "朋友",
  family: "家庭",
  water: "水",
  food: "食物",
  house: "房子",
  car: "车",
  book: "书",
  computer: "电脑",
  work: "工作",
  school: "学校",
  happy: "快乐",
  sad: "悲伤",
  big: "大",
  small: "小",
  beautiful: "美丽",
  welcome: "欢迎",
  how: "如何",
  what: "什么",
  where: "哪里",
  when: "什么时候",
  why: "为什么",
  who: "谁",
  the: "",
  and: "和",
  or: "或者",
  is: "是",
  are: "是",
  this: "这",
  that: "那",
  my: "我的",
  your: "你的",
  we: "我们",
  they: "他们",
  today: "今天",
  tomorrow: "明天",
  yesterday: "昨天",
};

const englishToKorean: Record<string, string> = {
  hello: "안녕하세요",
  goodbye: "안녕히 가세요",
  thank: "감사합니다",
  you: "당신",
  please: "제발",
  yes: "예",
  no: "아니요",
  good: "좋은",
  bad: "나쁜",
  morning: "아침",
  night: "밤",
  love: "사랑",
  friend: "친구",
  family: "가족",
  water: "물",
  food: "음식",
  house: "집",
  car: "차",
  book: "책",
  computer: "컴퓨터",
  work: "일",
  school: "학교",
  happy: "행복한",
  sad: "슬픈",
  big: "큰",
  small: "작은",
  beautiful: "아름다운",
  welcome: "환영",
  how: "어떻게",
  what: "무엇",
  where: "어디",
  when: "언제",
  why: "왜",
  who: "누구",
  the: "",
  and: "그리고",
  or: "또는",
  is: "이다",
  are: "이다",
  this: "이것",
  that: "그것",
  my: "내",
  your: "당신의",
  we: "우리",
  they: "그들",
  today: "오늘",
  tomorrow: "내일",
  yesterday: "어제",
};

const englishToRussian: Record<string, string> = {
  hello: "привет",
  goodbye: "до свидания",
  thank: "спасибо",
  you: "вы",
  please: "пожалуйста",
  yes: "да",
  no: "нет",
  good: "хороший",
  bad: "плохой",
  morning: "утро",
  night: "ночь",
  love: "любовь",
  friend: "друг",
  family: "семья",
  water: "вода",
  food: "еда",
  house: "дом",
  car: "машина",
  book: "книга",
  computer: "компьютер",
  work: "работа",
  school: "школа",
  happy: "счастливый",
  sad: "грустный",
  big: "большой",
  small: "маленький",
  beautiful: "красивый",
  welcome: "добро пожаловать",
  how: "как",
  what: "что",
  where: "где",
  when: "когда",
  why: "почему",
  who: "кто",
  the: "",
  and: "и",
  or: "или",
  is: "есть",
  are: "есть",
  this: "это",
  that: "то",
  my: "мой",
  your: "ваш",
  we: "мы",
  they: "они",
  today: "сегодня",
  tomorrow: "завтра",
  yesterday: "вчера",
};

const englishToArabic: Record<string, string> = {
  hello: "مرحبا",
  goodbye: "مع السلامة",
  thank: "شكرا",
  you: "أنت",
  please: "من فضلك",
  yes: "نعم",
  no: "لا",
  good: "جيد",
  bad: "سيء",
  morning: "صباح",
  night: "ليل",
  love: "حب",
  friend: "صديق",
  family: "عائلة",
  water: "ماء",
  food: "طعام",
  house: "بيت",
  car: "سيارة",
  book: "كتاب",
  computer: "حاسوب",
  work: "عمل",
  school: "مدرسة",
  happy: "سعيد",
  sad: "حزين",
  big: "كبير",
  small: "صغير",
  beautiful: "جميل",
  welcome: "أهلا وسهلا",
  how: "كيف",
  what: "ما",
  where: "أين",
  when: "متى",
  why: "لماذا",
  who: "من",
  the: "",
  and: "و",
  or: "أو",
  is: "هو",
  are: "هم",
  this: "هذا",
  that: "ذلك",
  my: "بلدي",
  your: "لك",
  we: "نحن",
  they: "هم",
  today: "اليوم",
  tomorrow: "غدا",
  yesterday: "أمس",
};

const englishToHindi: Record<string, string> = {
  hello: "नमस्ते",
  goodbye: "अलविदा",
  thank: "धन्यवाद",
  you: "आप",
  please: "कृपया",
  yes: "हाँ",
  no: "नहीं",
  good: "अच्छा",
  bad: "बुरा",
  morning: "सुबह",
  night: "रात",
  love: "प्यार",
  friend: "दोस्त",
  family: "परिवार",
  water: "पानी",
  food: "खाना",
  house: "घर",
  car: "गाड़ी",
  book: "किताब",
  computer: "कंप्यूटर",
  work: "काम",
  school: "स्कूल",
  happy: "खुश",
  sad: "दुखी",
  big: "बड़ा",
  small: "छोटा",
  beautiful: "सुंदर",
  welcome: "स्वागत है",
  how: "कैसे",
  what: "क्या",
  where: "कहाँ",
  when: "कब",
  why: "क्यों",
  who: "कौन",
  the: "",
  and: "और",
  or: "या",
  is: "है",
  are: "हैं",
  this: "यह",
  that: "वह",
  my: "मेरा",
  your: "आपका",
  we: "हम",
  they: "वे",
  today: "आज",
  tomorrow: "कल",
  yesterday: "कल",
};

export const languages: Language[] = [
  { code: "en", name: "English", dictionary: {} },
  { code: "es", name: "Spanish", dictionary: englishToSpanish },
  { code: "fr", name: "French", dictionary: englishToFrench },
  { code: "de", name: "German", dictionary: englishToGerman },
  { code: "ja", name: "Japanese", dictionary: englishToJapanese },
  { code: "it", name: "Italian", dictionary: englishToItalian },
  { code: "pt", name: "Portuguese", dictionary: englishToPortuguese },
  { code: "zh", name: "Chinese", dictionary: englishToChinese },
  { code: "ko", name: "Korean", dictionary: englishToKorean },
  { code: "ru", name: "Russian", dictionary: englishToRussian },
  { code: "ar", name: "Arabic", dictionary: englishToArabic },
  { code: "hi", name: "Hindi", dictionary: englishToHindi },
];

// Build reverse dictionaries for bidirectional translation
const buildReverseDictionary = (
  dict: Record<string, string>
): Record<string, string> => {
  const reverse: Record<string, string> = {};
  for (const [key, value] of Object.entries(dict)) {
    reverse[value] = key;
  }
  return reverse;
};

// Translation function with dictionary lookup
export function translateText(
  text: string,
  sourceLang: string,
  targetLang: string
): string {
  const words = text.toLowerCase().split(/\s+/);
  const sourceLanguage = languages.find(
    (l) => l.name.toLowerCase() === sourceLang.toLowerCase()
  );
  const targetLanguage = languages.find(
    (l) => l.name.toLowerCase() === targetLang.toLowerCase()
  );

  if (!sourceLanguage || !targetLanguage) {
    return text;
  }

  // If source is English, use direct dictionary
  if (sourceLang.toLowerCase() === "english") {
    const dict = targetLanguage.dictionary;
    return words
      .map((word) => dict[word] || word)
      .join(" ");
  }

  // If target is English, use reverse dictionary
  if (targetLang.toLowerCase() === "english") {
    const reverseDict = buildReverseDictionary(sourceLanguage.dictionary);
    return words
      .map((word) => reverseDict[word] || word)
      .join(" ");
  }

  // For non-English to non-English, translate through English
  const sourceReverseDict = buildReverseDictionary(sourceLanguage.dictionary);
  const targetDict = targetLanguage.dictionary;

  return words
    .map((word) => {
      const englishWord = sourceReverseDict[word] || word;
      return targetDict[englishWord] || englishWord;
    })
    .join(" ");
}